language: python
python:
  - "2.7"
  - "3.6"
install:
  - "pip install -r requirements.txt"
  - "python setup.py install"
  - "pip install pytest"
  - "pip install pytest-cov"
  - "pip install coveralls"
script:
    py.test --cov --pyargs ratecounter
after_success:
    coveralls
