language: python
python:
  - "2.7"
  - "3.6"
install:
  - "python setup.py install"
  - "pip install pytest"
  - "pip install pytest-cov"
  - "pip install coveralls"
script:
    py.test --cov

after_success:
    coveralls
